apiVersion: v1
kind: Service
metadata:
  name: prom-svc1
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prom-svc2
spec:
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9090
      nodePort: 30090
  selector:
    app: prometheus
