apiVersion: v1
kind: Service
metadata:
  name: dk-svc1
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8080
  selector:
    app: dk
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dk-svc2
spec:
  type: NodePort
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8080
  selector:
    app: dk
# kubectl apply -f app-service.yaml
