apiVersion: v1
kind: Service
metadata:
  name: grafana-svc1
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc2
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3000
      nodePort: 32000
  selector:
    app: grafana
